name: Run tests and publish Allure report

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install
      
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: history
        
    - name: Copy Allure history to results
      if: always()
      run: npm run allure:copy-history

    - name: Run Playwright tests
      run: npm run test:headless
      
    - name: Build test report
      if: always()
      run: npm run allure:generate
        
    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
